### ISSUE TITLE
Huge gap in "Optional setup" between "Or via npm" and "Globally" when rendered out

### ISSUE THREAD

**Issue by Schlomon** [Schlomon/DashJS-TS-Tutorial#1]
[Using-DashJS-with-TypeScript-in-VSCode.md](https://github.com/Schlomon/DashJS-TS-Tutorial/blob/master/tools/site/codelabs/Using-DashJS-with-TypeScript-in-VSCode.md)
[rendered view](https://dashjsintypescript.000webhostapp.com/codelabs/Using-DashJS-with-TypeScript-in-VSCode/index.html?index=..%2F..index#3)

**Comment by riongull** [comment]
It must be a bug in Codelab's 'markdown to html' renderer. There's nothing wrong with the markdown (which is why Github renderer works just fine).  It's probably just not sophisticated enough to handle sub-bullets nicely.

By the way, the new location of `Using-DashJS-with-TypeScript-in-VSCode.md` is now https://github.com/Schlomon/DashJS-TS-Tutorial/blob/master/tools/site/codelabs/Using-DashJS-with-TypeScript-in-VSCode.md.  We might want to edit the link above real quick, even though we will close this soon.  Also, do we want to link directly there (to the file, not the folder) in https://github.com/Schlomon/DashJS-TS-Tutorial#direct-links.  And should we capitalize the readme's (i.e. `README.md`) so they follow GitHub's standard?  I'll make a quick PR with these if so.

**Comment by riongull** [comment]
I suggest we do away with all of the "Globally" options and just assume a project-specific install for typescript, dash, and tslint.  That will solve this issue. I'll make a PR if you agree.

**Comment by Schlomon** [comment]
> By the way, the new location of `Using-DashJS-with-TypeScript-in-VSCode.md` is now https://github.com/Schlomon/DashJS-TS-Tutorial/blob/master/tools/site/codelabs/Using-DashJS-with-TypeScript-in-VSCode.md. We might want to edit the link above real quick, even though we will close this soon. Also, do we want to link directly there (to the file, not the folder) in https://github.com/Schlomon/DashJS-TS-Tutorial#direct-links. And should we capitalize the readme's (i.e. `README.md`) so they follow GitHub's standard? I'll make a quick PR with these if so.

Renamed readme and and updated the link (see 8ec98bf68a4bebfb5fc15c62a72f067206771ab5)
Maybe create a new issue for something like this next time, otherwise it can get quite messy.
