### ISSUE TITLE
Inconsistent use of single and triple backticks for codeblocks.

### ISSUE THREAD

**Issue by Schlomon** [Schlomon/DashJS-TS-Tutorial#5]
The use of ` and ``` is really inconsistent at the moment. We should determine some kind of convention.

So here is what I would suggest:
1. Every path and shortcut gets surrounded by only one backtick.
2. All commands for the command-line also get only one backtick but they're always in a new line.
3. Everything else (e.g. actual code, files-structures, etc.) get the triple backticks. (Which automatically results in a new line)

Examples:
1. Open the file `dir1/dir2/file1`, edit it and press `Ctrl` + `S` to save.

2. To install dash execute:
    `npm install --save-dev dash`

3. Import DashSDK with:
    ```typescript
    import * as Dash from "dash";
    ```

I haven't found any "official conventions", so this is just a suggestion.

**Comment by riongull** [comment]
Yeah, it's pretty inconsistent across the whole web to be honest, but I think it's uncontroversial to use single back ticks for inline files/directories/commands/etc and triple back ticks for code blocks.  

Regarding your specific suggestions, I would lean more towards single line shell commands to be inline but let me go review the examples in this repo and think it over...

**Comment by Schlomon** [comment]
I've put 1. and 3. only for completeness. 2. Is the only one we have to standardize.

**Comment by riongull** [comment]
I just read through the updated tutorial now that it's hosted and yeah, we definitely need to come up with a consistent method.  The differences are very obvious on this Codeblock site because it formats code blocks with black background and inline code with gray.  I personally prefer to see a code block only when there's a multiline block of code (Typescript) or code output, I think code blocks are overkill for both single-line shell instructions and single-line TS/JS code, which is why I refactored [step 6 of the tutorial](https://dashjsintypescript.000webhostapp.com/codelabs/Using-DashJS-with-TypeScript-in-VSCode/index.html?index=..%2F..index#5) to be what it is now (with the `import * as Dash from 'dash'` no longer stand-alone as it is in your item 3 above).  I guess we'd need others to chime in to break the tie on this.

**Comment by riongull** [comment]
@cloudwheels, perhaps you could weigh in on this.  It's not a big deal, but curious to hear your thoughts.

**Comment by Schlomon** [comment]
Agreeing on @riongull's [suggestion](https://github.com/Schlomon/Dash-Codelab-Tutorials/issues/5#issuecomment-661160302), implemented with commit 97cd569.
